routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);

Auth::routes();
Route::get('/logout', [App\Http\Controllers\Auth\LoginController::class, 'logout']);

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function(){

    Route::resource('category', App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('item', App\Http\Controllers\Admin\ItemController::class);
    Route::resource('supplier', App\Http\Controllers\Admin\SupplierController::class);
    Route::resource('customer', App\Http\Controllers\Admin\CustomerController::class);
    Route::resource('designation', App\Http\Controllers\Admin\DesignationController::class);
    Route::resource('opening-stock', App\Http\Controllers\Admin\OpeningStockController::class);
    Route::resource('stock-reject', App\Http\Controllers\Admin\StockRejectController::class);
    Route::resource('purchase', App\Http\Controllers\Admin\PurchaseController::class);
    Route::post('purchase/{purchase}/item/store', [App\Http\Controllers\Admin\PurchaseController::class, 'storeItem'])->name('purchase.item.store');
    Route::put('item-update/{purhaseDetails}', [App\Http\Controllers\Admin\PurchaseController::class, 'itemUpdate'])->name('item-update');
    Route::get('purchase/{purchase}/items', [App\Http\Controllers\Admin\PurchaseController::class, 'purchaseItem'])->name('purchase.item');
    Route::get('purchase/{purchase}/item/{purchaseDetails}/edit', [App\Http\Controllers\Admin\PurchaseController::class, 'itemEdit'])->name('purchase.details.edit');
    Route::get('purchase/{purchase}/item/{purchaseDetails}/delete', [App\Http\Controllers\Admin\PurchaseController::class, 'detailsDestroy'])->name('purchase.details.destroy');
    Route::get('items-by-category/{catId}', [App\Http\Controllers\Admin\OpeningStockController::class, 'itemsByCategory'])->name('items-by-category');
    Route::get('item-info/{itemId}', [App\Http\Controllers\Admin\PurchaseController::class, 'itemInfo'])->name('item-info');
    Route::resource('bill-payment', App\Http\Controllers\Admin\BillPaymentController::class);
    Route::get('invoice_due/{purchase_id}', [App\Http\Controllers\Admin\BillPaymentController::class, 'invoiceDue'])->name('invoice_due');

    Route::resource('sales', App\Http\Controllers\Admin\SalesController::class);
    Route::post('sales/{sale}/item/store', [App\Http\Controllers\Admin\SalesController::class, 'storeItem'])->name('sales.item.store');
    Route::put('sale-item-update/{salesDetails}', [App\Http\Controllers\Admin\SalesController::class, 'itemUpdate'])->name('sale-item-update');
    Route::get('sales/{sale}/items', [App\Http\Controllers\Admin\SalesController::class, 'salesItem'])->name('sales.item');
    Route::get('sales/{sale}/item/{salesDetails}/edit', [App\Http\Controllers\Admin\SalesController::class, 'itemEdit'])->name('sales.details.edit');
    Route::get('sales/{sale}/item/{salesDetails}/delete', [App\Http\Controllers\Admin\SalesController::class, 'detailsDestroy'])->name('sales.details.destroy');

    Route::resource('money-receipt', App\Http\Controllers\Admin\MoneyReceiptController::class);
    Route::get('sale_invoice_due/{sale_id}', [App\Http\Controllers\Admin\MoneyReceiptController::class, 'invoiceDue'])->name('invoice_due');

});

/*Route::get('admin/bill-payment', function () {
    return view('admin/bill_payment');
});*/

/*Route::get('admin/sales-list', function () {
    return view('admin/sales_list');
});
Route::get('admin/sales', function () {
    return view('admin/sales');
});*/
Route::get('admin/sales-expense', function () {
    return view('admin/sales_expense');
});
/*Route::get('admin/money-receipt', function () {
    return view('admin/money_receipt');
});*/
Route::get('admin/gate-pass', function () {
    return view('admin/gate_pass');
});
Route::get('admin/servicing-request', function () {
    return view('admin/servicing_request');
});
Route::get('admin/engineer-assign', function () {
    return view('admin/engineer_assign');
});
Route::get('admin/get-challan', function () {
    return view('admin/get_challan');
});
Route::get('admin/stuff', function () {
    return view('admin/stuff');
});
Route::get('admin/attendance', function () {
    return view('admin/attendance');
});
Route::get('admin/leave', function () {
    return view('admin/leave');
});
Route::get('admin/salary', function () {
    return view('admin/salary');
});
Route::get('admin/account-head', function () {
    return view('admin/account_head');
});
Route::get('admin/expense', function () {
    return view('admin/expense');
});
Route::get('admin/stuff-payment', function () {
    return view('admin/stuff_payment');
});
Route::get('admin/s', function () {
    return view('admin/salary');
});
Route::get('admin/salary-generate', function () {
    return view('admin/salary_generate');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function(){
	Route::get('/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index']);
	//Route::get('/category', [App\Http\Controllers\Admin\DashboardController::class, 'index']);

	Route::get('/user', function () {
		return Auth::user();
	});
});

app/Models/BillPayment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class BillPayment extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $fillable = ['date', 'supplier_id', 'purchase_id', 'amount', 'description'];

    public function supplier()
    {
        return $this->belongsTo(Supplier::class)->select('id', 'name');

    }
}

app/Http/Controllers/Admin/BillPaymentController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\BillPayment;
use App\Models\Purchase;
use App\Models\PurchaseDetails;
use App\Models\Supplier;
use Auth;
use Illuminate\Http\Request;
use DB;
use Exception;

class BillPaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['billPayments'] = BillPayment::with('supplier')->paginate(20);
        return view('admin.bill_payment.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['suppliers'] = Supplier::pluck('name', 'id');
        return view('admin/bill_payment/create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'date' => ['required', 'string', 'max:50'],
                'supplier_id' => ['required', 'integer', 'max:10'],
                'purchase_id' => ['required', 'integer', 'max:50'],
                'amount' => ['required'],
            ]
        );
        $billpayment = new BillPayment();
        $billpayment->fill($request->all());
        $billpayment->created_by = Auth::user()->id;
        $billpayment->save();

        toast('Data save successfully!', 'success');

        return back();
    }

     /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(BillPayment $billPayment)
    {
        $data['suppliers'] = Supplier::pluck('name', 'id');
        $invoiceTotal = Purchase::where('id', $billPayment->purchase_id)->sum('grant_total');
        $PaymentTotal = BillPayment::where('purchase_id', $billPayment->purchase_id)->sum('amount');

        $totalDue = ($invoiceTotal - $PaymentTotal);
        $data['totalDue'] = $totalDue;
        $data['billPayment'] = $billPayment;

        return view('admin/bill_payment/edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, BillPayment $billPayment)
    {
        $request->validate(
            [
                'date' => ['required', 'string', 'max:50'],
                'supplier_id' => ['required', 'integer', 'max:10'],
                'purchase_id' => ['required', 'integer', 'max:50'],
                'amount' => ['required'],
            ]
        );
        $billPayment->fill($request->all());
        $billPayment->created_by = Auth::user()->id;
        $billPayment->save();

        toast('Data update successfully!', 'success');

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(BillPayment $billPayment)
    {
        $billPayment->delete();
        toast('Bill Payment has been deleted successfully!', 'success');

        return redirect()->route('bill-payment.index');
    }

    public function invoiceDue($purchase_id)
    {
        $invoiceTotal = Purchase::where('id', $purchase_id)->sum('grant_total');
        $PaymentTotal = BillPayment::where('purchase_id', $purchase_id)->sum('amount');

        $totalDue = ($invoiceTotal - $PaymentTotal);
        $due = array('totaldue' => $totalDue);

        return response()->json($due);
    }
}

resources/views/admin/bill_payment/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Admin</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Bill Payment</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">
                                    Add Bill Payment
                                    <a href="{{ route('bill-payment.index') }}" class="btn btn-primary btn-sm pull-right">
                                        <i class="la flaticon-back"></i> Back</a>
                                </div>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'bill-payment.store']) !!}

                                @include('admin.bill_payment.form')

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

@endsection

resources/views/admin/bill_payment/invoice_details.blade.php
@extends('layouts.admin')

@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Admin</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Purchases</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">
                                    Purchase
                                    <a href="{{ route('purchase.create') }}" class="btn btn-primary btn-sm pull-right">
                                        <i class="fas fa-plus-circle"></i> add
                                    </a>
                                </div>
                            </div>
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Item Name</th>
                                        <th>Item Type</th>
                                        <th>Quantity</th>
                                        <th>Rate</th>
                                        <th>Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($purchaseDetails as $index => $v)
                                        <tr>
                                            <th scope="row">{{ $index +1 }}</th>
                                            <td>{{ $v->item->item_name }}</td>
                                            <td>
                                                @if($v->item_type == 1)
                                                    Machinaries
                                                @else
                                                    Spare Parts
                                                @endif
                                            </td>
                                            <td>{{ $v->quantity }}</td>
                                            <td>{{ $v->unit_price }}</td>
                                            <td>{{ $v->total }}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('js')
   <script>
        // mortgage approval
        $(document).on('click', '.delete-button', function (e) {
            e.preventDefault();
            var _this = $(this);
            Swal.fire({
                title: "Are you sure to delete",
                icon: "warning",
                confirmButtonText: 'Confirm',
                showCancelButton: true,
            }).then(function (result) {
                if (result.isConfirmed) _this.closest('form').submit();
            });
            $('.date').datepicker({
                format: 'mm-dd-yyyy'
            });
        });
    </script>
@endpush

resources/views/admin/bill_payment/list.blade.php
@extends('layouts.admin')

@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Admin</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Bill Payment</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">
                                    Bill Payment
                                    <a href="{{ route('bill-payment.create') }}" class="btn btn-primary btn-sm pull-right">
                                        <i class="fas fa-plus-circle"></i> add
                                    </a>
                                </div>
                            </div>
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Date</th>
                                        <th>Supplier Name</td>
                                        <th>Amount</th>
                                        <th>Remarks</th>
                                        <th width="140">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($billPayments as $index => $v)
                                        <tr>
                                            <th scope="row">{{ $billPayments->firstItem() + $index }}</th>
                                            <td>{{ $v->date }}</td>
                                            <td>{{ $v->supplier->name }}</td>
                                            <td>{{ $v->amount }}</td>
                                            <td>{{ $v->description }}</td>
                                            <td>
                                                <a href="{{ route('bill-payment.edit', $v->id) }}" class="btn btn-secondary btn-xs">
                                                    <i class="fas fa-pen-square" title="Edit"></i>
                                                </a>
                                                <form class="d-inline" action="{{ route('bill-payment.destroy', $v->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit" class="btn btn-danger btn-xs delete-button">
                                                        <i class="fas fa-trash-alt" title="Delete"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                {!! $billPayments->links() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('js')
   <script>
        // mortgage approval
        $(document).on('click', '.delete-button', function (e) {
            e.preventDefault();
            var _this = $(this);
            Swal.fire({
                title: "Are you sure to delete",
                icon: "warning",
                confirmButtonText: 'Confirm',
                showCancelButton: true,
            }).then(function (result) {
                if (result.isConfirmed) _this.closest('form').submit();
            });
            $('.date').datepicker({
                format: 'mm-dd-yyyy'
            });
        });
    </script>
@endpush

resources/views/admin/bill_payment/purchase_item.blade.php
@extends('layouts.admin')
@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Admin</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Purchase</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">
                                    Add Purchase
                                    <a href="{{ route('purchase.index') }}" class="btn btn-primary btn-sm pull-right">
                                        <i class="la flaticon-back"></i> Back</a>
                                </div>
                            </div>
                            <div class="card-body">
                                <table class="table">
                                    <tr>
                                        <td>Date</td>
                                        <td>{{ $purchaseInfo->date }}</td>
                                        <td>Supplier</td>
                                        <td>{{ $purchaseInfo->supplier->name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Item Type</td>
                                        <td>
                                            @if($purchaseInfo->item_type == 1)
                                                Machinaries
                                            @else
                                                Spare Parts
                                            @endif
                                        </td>
                                        <td>Discount</td>
                                        <td>{{ $purchaseInfo->discount }}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="card">
                            <div class="card-body">
                                @if(!empty($purhaseDetails))
                                    {!! Form::model($purhaseDetails, ['route' => ['item-update', $purhaseDetails->id]]) !!}
                                    @method('put')
                                @else
                                {!! Form::open(['route' => ['purchase.item.store', $purchaseInfo->id]]) !!}
                                @endif
                                <div class="form-group">
                                    {!! Form::label('category_id', 'Category') !!}
                                    {!! Form::select('category_id', $categories, null, ['id' => 'category_id', 'placeholder'=>'Select Category','class' => 'form-control']) !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::label('item_id', 'Item') !!}
                                    {!! Form::select('item_id', $items, null, ['id' => 'item_id', 'placeholder'=>'Select Item','class' => 'form-control']) !!}
                                    @error('item_id')
                                    <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    {!! Form::label('quantity', 'Quantity') !!}
                                    {!! Form::number('quantity', null, ['id' => 'quantity', 'placeholder'=>'Quantity','class' => 'form-control']) !!}
                                    @error('quantity')
                                    <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    {!! Form::label('unit_price', 'Unit Price') !!}
                                    {!! Form::number('unit_price', null, ['id' => 'unit_price', 'placeholder'=>'Unit Price','class' => 'form-control']) !!}
                                    @error('unit_price')
                                    <div class="text-danger">{{ $message }}</div>
                                    @enderror
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> add</button>
                                        </div>
                                    </div>
                                </div>

                                    {!! Form::close() !!}
                            </div>
                        </div>
                        </div>
                        <div class="col-md-7">
                            <div class="card">
                                <div class="card-body">
                                    <table  class="table table-bordered">
                                        <thead>
                                        <th>Item</th>
                                        <th>Quantity</th>
                                        <th>Unit Price</th>
                                        <th>Total</th>
                                        <th>Action</th>
                                        </thead>
                                        <tbody class="item-table">
                                        @foreach($purchaseList as $index => $v)
                                            <tr>
                                                <td>{{ $v->item->item_name }}</td>
                                                <td>{{ $v->quantity }}</td>
                                                <td>{{ $v->unit_price }}</td>
                                                <td>{{ $v->total }}</td>
                                                <td>
                                                    <a href="{{ route('purchase.details.edit', [$purchaseInfo->id, $v->id]) }}" class="item-edit btn btn-success btn-xs ">
                                                        <i class="fas fa-pen-square" title="Edit"></i>
                                                    </a>
                                                   &nbsp;||&nbsp;

                                                    <form class="d-inline" action="{{ route('purchase.details.destroy', [$purchaseInfo->id, $v->id]) }}" method="post">
                                                        @csrf
                                                        @method('get')
                                                        <button type="submit" class="btn btn-danger btn-xs delete-button">
                                                            <i class="fas fa-trash-alt" title="Delete"></i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        // mortgage approval
        $(document).on('click', '.delete-button', function (e) {
            e.preventDefault();
            var _this = $(this);
            Swal.fire({
                title: "Are you sure to delete",
                icon: "warning",
                confirmButtonText: 'Confirm',
                showCancelButton: true,
            }).then(function (result) {
                if (result.isConfirmed) _this.closest('form').submit();
            });
        });

        $('#category_id').on('change', function (){
            var category_id = $(this).val();
            $.ajax({
                url:"{{url('admin/items-by-category')}}/"+category_id,
                type:"GET",
                dataType:'json',
                success:function(data){
                    $('#item_id').html('<option value="">Select Item</option>')
                    $.each( data, function( key, value) {
                        $('#item_id').append('<option value="'+value.id+'">'+value.item_name+'</option>')
                    });
                }
            });
        });
    </script>
@endpush