routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);

Auth::routes();
Route::get('/logout', [App\Http\Controllers\Auth\LoginController::class, 'logout']);

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function(){

    Route::resource('category', App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('item', App\Http\Controllers\Admin\ItemController::class);
    Route::resource('supplier', App\Http\Controllers\Admin\SupplierController::class);
    Route::resource('customer', App\Http\Controllers\Admin\CustomerController::class);
    Route::resource('designation', App\Http\Controllers\Admin\DesignationController::class);
    Route::resource('opening-stock', App\Http\Controllers\Admin\OpeningStockController::class);
    Route::resource('stock-reject', App\Http\Controllers\Admin\StockRejectController::class);
    Route::resource('purchase', App\Http\Controllers\Admin\PurchaseController::class);
    Route::post('purchase/{purchase}/item/store', [App\Http\Controllers\Admin\PurchaseController::class, 'storeItem'])->name('purchase.item.store');
    Route::put('item-update/{purhaseDetails}', [App\Http\Controllers\Admin\PurchaseController::class, 'itemUpdate'])->name('item-update');
    Route::get('purchase/{purchase}/items', [App\Http\Controllers\Admin\PurchaseController::class, 'purchaseItem'])->name('purchase.item');
    Route::get('purchase/{purchase}/item/{purchaseDetails}/edit', [App\Http\Controllers\Admin\PurchaseController::class, 'itemEdit'])->name('purchase.details.edit');
    Route::get('purchase/{purchase}/item/{purchaseDetails}/delete', [App\Http\Controllers\Admin\PurchaseController::class, 'detailsDestroy'])->name('purchase.details.destroy');
    Route::get('items-by-category/{catId}', [App\Http\Controllers\Admin\OpeningStockController::class, 'itemsByCategory'])->name('items-by-category');
    Route::get('item-info/{itemId}', [App\Http\Controllers\Admin\PurchaseController::class, 'itemInfo'])->name('item-info');
    Route::resource('bill-payment', App\Http\Controllers\Admin\BillPaymentController::class);
    Route::get('invoice_due/{purchase_id}', [App\Http\Controllers\Admin\BillPaymentController::class, 'invoiceDue'])->name('invoice_due');

    Route::resource('sales', App\Http\Controllers\Admin\SalesController::class);
    Route::post('sales/{sale}/item/store', [App\Http\Controllers\Admin\SalesController::class, 'storeItem'])->name('sales.item.store');
    Route::put('sale-item-update/{salesDetails}', [App\Http\Controllers\Admin\SalesController::class, 'itemUpdate'])->name('sale-item-update');
    Route::get('sales/{sale}/items', [App\Http\Controllers\Admin\SalesController::class, 'salesItem'])->name('sales.item');
    Route::get('sales/{sale}/item/{salesDetails}/edit', [App\Http\Controllers\Admin\SalesController::class, 'itemEdit'])->name('sales.details.edit');
    Route::get('sales/{sale}/item/{salesDetails}/delete', [App\Http\Controllers\Admin\SalesController::class, 'detailsDestroy'])->name('sales.details.destroy');

    Route::resource('money-receipt', App\Http\Controllers\Admin\MoneyReceiptController::class);
    Route::get('sale_invoice_due/{sale_id}', [App\Http\Controllers\Admin\MoneyReceiptController::class, 'invoiceDue'])->name('invoice_due');

});

/*Route::get('admin/bill-payment', function () {
    return view('admin/bill_payment');
});*/

/*Route::get('admin/sales-list', function () {
    return view('admin/sales_list');
});
Route::get('admin/sales', function () {
    return view('admin/sales');
});*/
Route::get('admin/sales-expense', function () {
    return view('admin/sales_expense');
});
/*Route::get('admin/money-receipt', function () {
    return view('admin/money_receipt');
});*/
Route::get('admin/gate-pass', function () {
    return view('admin/gate_pass');
});
Route::get('admin/servicing-request', function () {
    return view('admin/servicing_request');
});
Route::get('admin/engineer-assign', function () {
    return view('admin/engineer_assign');
});
Route::get('admin/get-challan', function () {
    return view('admin/get_challan');
});
Route::get('admin/stuff', function () {
    return view('admin/stuff');
});
Route::get('admin/attendance', function () {
    return view('admin/attendance');
});
Route::get('admin/leave', function () {
    return view('admin/leave');
});
Route::get('admin/salary', function () {
    return view('admin/salary');
});
Route::get('admin/account-head', function () {
    return view('admin/account_head');
});
Route::get('admin/expense', function () {
    return view('admin/expense');
});
Route::get('admin/stuff-payment', function () {
    return view('admin/stuff_payment');
});
Route::get('admin/s', function () {
    return view('admin/salary');
});
Route::get('admin/salary-generate', function () {
    return view('admin/salary_generate');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function(){
	Route::get('/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index']);
	//Route::get('/category', [App\Http\Controllers\Admin\DashboardController::class, 'index']);

	Route::get('/user', function () {
		return Auth::user();
	});
});

app/Models/Purchase.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Purchase extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $fillable = ['date', 'voucher_no', 'item_type', 'supplier_id', 'discount', 'grant_total', 'description'];

    public function supplier()
    {
        return $this->belongsTo(Supplier::class)->select('id', 'name');

    }

    public function supplierInfo()
    {
        return $this->belongsTo(Supplier::class)->select('name', 'phone', 'email', 'company_name', 'contact_person', 'address');

    }
    public function categories()
    {
        return $this->belongsTo(Category::class)->select('id', 'category_name');

    }

    public function items()
    {
        return $this->belongsTo(Item::class)->select('id', 'item_name');

    }

    public function purchaseDetails()
    {
        return $this->hasMany(PurchaseDetails::class)->select('item_id', 'quantity', 'unit_price');
    }
}

app/Http/Controllers/Admin/PurchaseController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\BillPayment;
use App\Models\Item;
use App\Models\Category;
use App\Models\Purchase;
use App\Models\PurchaseDetails;
use App\Models\Stock;
use App\Models\Supplier;
use Auth;
use Illuminate\Http\Request;
use DB;
use Exception;

class PurchaseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $data['purchaseList'] = Purchase::with('supplier')->paginate(20);
        return view('admin.purchase.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['suppliers'] = Supplier::pluck('name', 'id');
        $data['categories'] = Category::pluck('category_name', 'id');
        $data['items'] = Item::pluck('item_name', 'id');

        return view('admin/purchase/create', $data);
    }

    public function purchaseItem(Purchase $purchase)
    {
        //dd($purchase);
        $data['purchaseList'] = purchaseDetails::with('item')->where('purchase_id', $purchase->id)->get();
        $data['categories'] = Category::pluck('category_name', 'id');
        $data['items'] = Item::pluck('item_name', 'id');
        $data['purchaseInfo'] = $purchase;
        //dd($data['purchaseInfo']);

        return view('admin/purchase/purchase_item', $data);
    }

    public function itemInfo($itemId)
    {
        $itemInfo = Item::where('id', $itemId)->first();
        return response()->json($itemInfo);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'date' => ['required', 'string', 'max:50'],
                'supplier_id' => ['required', 'integer', 'max:10'],
                'item_type' => ['required', 'integer'],
            ]
        );

        //dd($request);

        //try {
        //DB::beginTransaction();

        $purchase = new Purchase();
        $purchase->fill($request->all());
        $purchase->created_by = Auth::user()->id;
        $purchase->save();

        //$stock = Stock::addStock($request->item_id, $request->quantity);

        //DB::commit();

        toast('Please add your products!', 'success');

        return redirect()->route('purchase.item', $purchase->id);

        /*} catch (Exception $exception) {
            DB::rollback();
            toast($exception->getMessage(), 'error');
            return back();
        }*/
    }

    public function storeItem(Purchase $purchase, Request $request)
    {
        $request->validate(
            [
                'item_id' => ['required', 'integer'],
                'quantity' => ['required', 'integer'],
                'unit_price' => ['required', 'integer'],
            ]
        );

        //dd($request);

        try {
            DB::beginTransaction();

            $details = new PurchaseDetails();
            $details->fill($request->all());
            $details->purchase_id = $purchase->id;
            $details->total = $request->quantity * $request->unit_price;
            $details->created_by = Auth::user()->id;
            $details->save();

            $stock = Stock::addStock($request->item_id, $request->quantity);

            $total = PurchaseDetails::where('purchase_id', $purchase->id)->sum('total');

            //DB::enableQueryLog();
            $purchase->grant_total = $total - (($total * $purchase->discount)/100);
            $purchase->save();

            //dd(DB::getQueryLog());

            DB::commit();

            toast('Product successfully added', 'success');

            return redirect()->route('purchase.item', $purchase->id);

        } catch (Exception $exception) {
            DB::rollback();
            toast($exception->getMessage(), 'error');
            return back();
        }
    }

    public function itemUpdate(Request $request, PurchaseDetails $purhaseDetails)
    {

        $request->validate(
            [
                'item_id' => ['required','numeric', 'max:300'],
                'quantity' => ['required', 'numeric'],
                'unit_price' => ['required', 'numeric', 'digits_between:1,11'],
            ]
        );

        try {
            DB::beginTransaction();

            $oldQuantity = $purhaseDetails->quantity;
            $purhaseDetails->fill($request->all());
            $purhaseDetails->purchase_id = $purhaseDetails->purchase_id;
            $purhaseDetails->total = $request->quantity * $request->unit_price;
            $purhaseDetails->created_by = Auth::user()->id;
            $purhaseDetails->save();

            $stock = Stock::updateStock($request->item_id, $request->quantity, $oldQuantity);

            $purchase = Purchase::where('id', $purhaseDetails->purchase_id)->first();

            //dd($purchase);

            $total = PurchaseDetails::where('purchase_id', $purhaseDetails->purchase_id)->sum('total');

            //DB::enableQueryLog();
            $purchase->grant_total = $total - (($total * $purchase->discount)/100);
            $purchase->save();

            //dd(DB::getQueryLog());

            DB::commit();

            toast('Purchase Item successfully Update', 'success');

            return redirect()->route('purchase.item', $purhaseDetails->purchase_id);

        } catch (Exception $exception) {
            DB::rollback();
            toast($exception->getMessage(), 'error');
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['purchaseDetails'] = purchaseDetails::with('item')->where('purchase_id', $id)->get();
        $data['invoiceTotal']    = purchaseDetails::where('purchase_id', $id)->sum('total');
        $data['totalReceive']    = BillPayment::where('purchase_id', $id)->sum('amount');
        //DB::enableQueryLog();
        $data['purchase']        = Purchase::where('id', $id)->first();
        $data['supplierInfo']    = Supplier::where('id', $data['purchase']->supplier_id)->first();
        //dd(DB::getQueryLog());

        return view('admin/purchase/invoice_details', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Purchase $purchase)
    {
        //dd($purchase);
        $data['suppliers'] = Supplier::pluck('name', 'id');
        $data['categories'] = Category::pluck('category_name', 'id');
        $data['items'] = Item::pluck('item_name', 'id');
        $data['purchase'] = $purchase;
        return view('admin/purchase/edit', $data);
    }

    public function itemEdit(Purchase $purchase, PurchaseDetails $purchaseDetails)
    {
        $data['purchaseList'] = purchaseDetails::with('item')->where('purchase_id', $purchase->id)->get();
        $data['categories'] = Category::pluck('category_name', 'id');
        $data['items'] = Item::pluck('item_name', 'id');
        $data['purchaseInfo'] = $purchase;
        $item = Item::where('id', $purchaseDetails->item_id)->first();
        $purchaseDetails->category_id = $item->category_id;
        $data['purhaseDetails'] = $purchaseDetails;

        return view('admin/purchase/purchase_item', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Purchase $purchase)
    {
        //dd($purchase);
        $request->validate(
            [
                'date' => ['required', 'string', 'max:50'],
                'supplier_id' => ['required', 'integer', 'max:10'],
                'item_type' => ['required', 'integer'],
            ]
        );
        $total = PurchaseDetails::where('purchase_id', $purchase->id)->sum('total');

        //DB::enableQueryLog();
        $purchase->grant_total = $total - (($total * $purchase->discount)/100);
        $purchase->save();

        $purchase->fill($request->all());
        $purchase->created_by = Auth::user()->id;
        $purchase->save();


        toast('Purchase Update Successfully, Please edit your products!', 'success');

        return redirect()->route('purchase.item', $purchase->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Purchase $purchase)
    {

        foreach ($purchase->purchaseDetails as $item){

            $stock = Stock::deductStockReject($item->item_id, $item->quantity);
            $purchase->purchaseDetails()->delete();
        }
        $purchase->delete();

        toast('Purchase has been deleted successfully!', 'success');

        return redirect()->route('purchase.index');
    }

    public function detailsDestroy(Purchase $purchase, PurchaseDetails $purchaseDetails)
    {
        //dd($purchaseDetails);
        $stock = Stock::deductStockReject($purchaseDetails->item_id, $purchaseDetails->quantity);
        $purchaseDetails->delete();

        toast('Item Deduct successfully!', 'success');

        return redirect()->route('purchase.item', $purchase->id);
    }

    public function itemsByCategory($catId)
    {
        $items = Item::where('category_id', $catId)->get();

        return response()->json($items);
    }
}

resources/views/admin/purchase/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Admin</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Purchase</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">
                                    Add Purchase
                                    <a href="{{ route('purchase.index') }}" class="btn btn-primary btn-sm pull-right">
                                        <i class="la flaticon-back"></i> Back</a>
                                </div>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'purchase.store']) !!}

                                @include('admin.purchase.form')

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

@endsection

resources/views/admin/purchase/invoice_details.blade.php
@extends('layouts.admin')

@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Admin</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Purchases</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">
                                    Purchase
                                    <a href="{{ route('purchase.create') }}" class="btn btn-primary btn-sm pull-right">
                                        <i class="fas fa-plus-circle"></i> add
                                    </a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row mb-4">
                                    <div class="col-sm-6">
                                        <h2>Bill To:</h2>
                                        Photo Lab Limited<br>
                                        Badda, Dhaka<br>
                                        01912756614
                                    </div>
                                    <div class="col-sm-6">
                                        Date:{{ date('Y-m-d') }}<br>
                                        Sales Person: {{ $supplierInfo->name }}<br>
                                        Invoice No # {{ $purchase->id }}
                                    </div>
                                </div>
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Item Name</th>
                                        <th>Item Type</th>
                                        <th class="text-right">Quantity</th>
                                        <th class="text-right">Rate</th>
                                        <th class="text-right">Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($purchaseDetails as $index => $v)
                                        <tr>
                                            <th scope="row">{{ $index +1 }}</th>
                                            <td>{{ $v->item->item_name }}</td>
                                            <td>
                                                @if($v->item_type == 1)
                                                    Machinaries
                                                @else
                                                    Spare Parts
                                                @endif
                                            </td>
                                            <td class="text-right">{{ $v->quantity }}</td>
                                            <td class="text-right">{{ $v->unit_price }}</td>
                                            <td class="text-right">{{ $v->total }}</td>
                                        </tr>
                                    @endforeach
                                    <tr>
                                        <td colspan="5" class="text-right">Sub Total</td>
                                        <td class="text-right">{{ $invoiceTotal }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="5" class="text-right">Discount(- {{ $purchase->discount }} %)</td>
                                        <td class="text-right">{{ $invoiceTotal * $purchase->discount / 100 }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="5" class="text-right">Grand Total</td>
                                        <td class="text-right">{{ $purchase->grant_total }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="5" class="text-right">Received</td>
                                        <td class="text-right">{{ $totalReceive }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="5" class="text-right">Due</td>
                                        <td class="text-right">{{ $purchase->grant_total - $totalReceive }}</td>
                                    </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('js')
   <script>
        // mortgage approval
        $(document).on('click', '.delete-button', function (e) {
            e.preventDefault();
            var _this = $(this);
            Swal.fire({
                title: "Are you sure to delete",
                icon: "warning",
                confirmButtonText: 'Confirm',
                showCancelButton: true,
            }).then(function (result) {
                if (result.isConfirmed) _this.closest('form').submit();
            });
            $('.date').datepicker({
                format: 'mm-dd-yyyy'
            });
        });
    </script>
@endpush

resources/views/admin/purchase/list.blade.php
@extends('layouts.admin')

@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Admin</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Purchases</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">
                                    Purchase
                                    <a href="{{ route('purchase.create') }}" class="btn btn-primary btn-sm pull-right">
                                        <i class="fas fa-plus-circle"></i> add
                                    </a>
                                </div>
                            </div>
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Date</th>
                                        <th>Supplier Name</th>
                                        <th>Item Type</th>
                                        <th>Discount</th>
                                        <th>Grand Total</th>
                                        <th>Remarks</th>
                                        <th width="140">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($purchaseList as $index => $v)
                                        <tr>
                                            <th scope="row">{{ $purchaseList->firstItem() + $index }}</th>
                                            <td>{{ $v->date }}</td>
                                            <td>{{ $v->supplier->name }}</td>
                                            <td>
                                                @if($v->item_type == 1)
                                                    Machinaries
                                                @else
                                                    Spare Parts
                                                @endif
                                            </td>
                                            <td>{{ $v->discount }}</td>
                                            <td>{{ $v->grant_total }}</td>
                                            <td>{{ $v->description }}</td>
                                            <td>
                                                <a href="{{ route('purchase.edit', $v->id) }}" class="btn btn-secondary btn-xs">
                                                    <i class="fas fa-pen-square" title="Edit"></i>
                                                </a>
                                            <!--<a href="{{ route('purchase.item', $v->id) }}" class="btn btn-secondary btn-xs">
                                                    <i class="fas fa-pen-square" title="Edit"></i>
                                                </a>-->

                                                <form class="d-inline" action="{{ route('purchase.destroy', $v->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit" class="btn btn-danger btn-xs delete-button">
                                                        <i class="fas fa-trash-alt" title="Delete"></i>
                                                    </button>
                                                </form>
                                                <a href="{{ route('purchase.show', $v->id) }}" class="btn btn-primary btn-xs">
                                                    <i class="la flaticon-medical" title="View"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                {!! $purchaseList->links() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('js')
   <script>
        // mortgage approval
        $(document).on('click', '.delete-button', function (e) {
            e.preventDefault();
            var _this = $(this);
            Swal.fire({
                title: "Are you sure to delete",
                icon: "warning",
                confirmButtonText: 'Confirm',
                showCancelButton: true,
            }).then(function (result) {
                if (result.isConfirmed) _this.closest('form').submit();
            });
            $('.date').datepicker({
                format: 'mm-dd-yyyy'
            });
        });
    </script>
@endpush