routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [App\Http\Controllers\Auth\LoginController::class, 'showLoginForm']);

Auth::routes();
Route::get('/logout', [App\Http\Controllers\Auth\LoginController::class, 'logout']);

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function(){

    Route::resource('category', App\Http\Controllers\Admin\CategoryController::class);
    Route::resource('item', App\Http\Controllers\Admin\ItemController::class);
    Route::resource('supplier', App\Http\Controllers\Admin\SupplierController::class);
    Route::resource('customer', App\Http\Controllers\Admin\CustomerController::class);
    Route::resource('designation', App\Http\Controllers\Admin\DesignationController::class);
    Route::resource('opening-stock', App\Http\Controllers\Admin\OpeningStockController::class);
    Route::resource('stock-reject', App\Http\Controllers\Admin\StockRejectController::class);
    Route::resource('purchase', App\Http\Controllers\Admin\PurchaseController::class);
    Route::post('purchase/{purchase}/item/store', [App\Http\Controllers\Admin\PurchaseController::class, 'storeItem'])->name('purchase.item.store');
    Route::put('item-update/{purhaseDetails}', [App\Http\Controllers\Admin\PurchaseController::class, 'itemUpdate'])->name('item-update');
    Route::get('purchase/{purchase}/items', [App\Http\Controllers\Admin\PurchaseController::class, 'purchaseItem'])->name('purchase.item');
    Route::get('purchase/{purchase}/item/{purchaseDetails}/edit', [App\Http\Controllers\Admin\PurchaseController::class, 'itemEdit'])->name('purchase.details.edit');
    Route::get('purchase/{purchase}/item/{purchaseDetails}/delete', [App\Http\Controllers\Admin\PurchaseController::class, 'detailsDestroy'])->name('purchase.details.destroy');
    Route::get('items-by-category/{catId}', [App\Http\Controllers\Admin\OpeningStockController::class, 'itemsByCategory'])->name('items-by-category');
    Route::get('item-info/{itemId}', [App\Http\Controllers\Admin\PurchaseController::class, 'itemInfo'])->name('item-info');
    Route::resource('bill-payment', App\Http\Controllers\Admin\BillPaymentController::class);
    Route::get('invoice_due/{purchase_id}', [App\Http\Controllers\Admin\BillPaymentController::class, 'invoiceDue'])->name('invoice_due');

    Route::resource('sales', App\Http\Controllers\Admin\SalesController::class);
    Route::post('sales/{sale}/item/store', [App\Http\Controllers\Admin\SalesController::class, 'storeItem'])->name('sales.item.store');
    Route::put('sale-item-update/{salesDetails}', [App\Http\Controllers\Admin\SalesController::class, 'itemUpdate'])->name('sale-item-update');
    Route::get('sales/{sale}/items', [App\Http\Controllers\Admin\SalesController::class, 'salesItem'])->name('sales.item');
    Route::get('sales/{sale}/item/{salesDetails}/edit', [App\Http\Controllers\Admin\SalesController::class, 'itemEdit'])->name('sales.details.edit');
    Route::get('sales/{sale}/item/{salesDetails}/delete', [App\Http\Controllers\Admin\SalesController::class, 'detailsDestroy'])->name('sales.details.destroy');

    Route::resource('money-receipt', App\Http\Controllers\Admin\MoneyReceiptController::class);
    Route::get('sale_invoice_due/{sale_id}', [App\Http\Controllers\Admin\MoneyReceiptController::class, 'invoiceDue'])->name('invoice_due');

});

/*Route::get('admin/bill-payment', function () {
    return view('admin/bill_payment');
});*/

/*Route::get('admin/sales-list', function () {
    return view('admin/sales_list');
});
Route::get('admin/sales', function () {
    return view('admin/sales');
});*/
Route::get('admin/sales-expense', function () {
    return view('admin/sales_expense');
});
/*Route::get('admin/money-receipt', function () {
    return view('admin/money_receipt');
});*/
Route::get('admin/gate-pass', function () {
    return view('admin/gate_pass');
});
Route::get('admin/servicing-request', function () {
    return view('admin/servicing_request');
});
Route::get('admin/engineer-assign', function () {
    return view('admin/engineer_assign');
});
Route::get('admin/get-challan', function () {
    return view('admin/get_challan');
});
Route::get('admin/stuff', function () {
    return view('admin/stuff');
});
Route::get('admin/attendance', function () {
    return view('admin/attendance');
});
Route::get('admin/leave', function () {
    return view('admin/leave');
});
Route::get('admin/salary', function () {
    return view('admin/salary');
});
Route::get('admin/account-head', function () {
    return view('admin/account_head');
});
Route::get('admin/expense', function () {
    return view('admin/expense');
});
Route::get('admin/stuff-payment', function () {
    return view('admin/stuff_payment');
});
Route::get('admin/s', function () {
    return view('admin/salary');
});
Route::get('admin/salary-generate', function () {
    return view('admin/salary_generate');
});

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function(){
	Route::get('/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index']);
	//Route::get('/category', [App\Http\Controllers\Admin\DashboardController::class, 'index']);

	Route::get('/user', function () {
		return Auth::user();
	});
});

app/Models/StockReject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class StockReject extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $fillable = ['category_id', 'item_id', 'date', 'quantity', 'description', 'status'];
    public function category()
    {
        return $this->belongsTo(Category::class)->select('id', 'category_name');

    }

    public function item()
    {
        return $this->belongsTo(Item::class)->select('id', 'item_name');

    }


}

app/Http/Controllers/Admin/StockRejectController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Item;
use App\Models\Category;
use App\Models\StockReject;
use App\Models\Stock;
use Auth;
use Illuminate\Http\Request;
use DB;
use Exception;

class StockRejectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $data['stockRejects'] = StockReject::with('category')->with('item')->paginate(20);
        return view('admin.stock_reject.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['categories'] = Category::pluck('category_name', 'id');
        $data['items'] = Item::pluck('item_name', 'id');

        return view('admin/stock_reject/create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'category_id' => ['required', 'string', 'max:300'],
                'item_id' => ['required', 'string', 'max:300'],
                'quantity' => ['required', 'integer'],
            ]
        );

        try {
            DB::beginTransaction();

            $stockReject = new StockReject();
            $stockReject->fill($request->all());
            $stockReject->date = date('Y-m-d');
            $stockReject->created_by = Auth::user()->id;
            $stockReject->save();

            $stock = Stock::deductStockReject($request->item_id, $request->quantity);

            DB::commit();

            toast('Stock reject has been save successfully!', 'success');

            return redirect()->route('stock-reject.index');

        } catch (Exception $exception) {
            DB::rollback();
            toast($exception->getMessage(), 'error');
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(StockReject $stockReject)
    {
        $data['categories'] = Category::pluck('category_name', 'id');
        $data['items'] = Item::pluck('item_name', 'id');
        $data['stockReject']  = $stockReject;
        return view('admin/stock_reject/edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, StockReject $stockReject)
    {
        $request->validate(
            [
                'category_id' => ['required', 'string', 'max:300'],
                'item_id' => ['required', 'string', 'max:300'],
                'quantity' => ['required', 'integer'],
            ]
        );
        try {
            DB::beginTransaction();

            $oldQuantity = $stockReject->quantity;
            $stockReject->fill($request->all());
            $stockReject->date = date('Y-m-d');
            $stockReject->created_by = Auth::user()->id;
            $stockReject->save();

            $stock = Stock::updateStockReject($request->item_id, $request->quantity, $oldQuantity);

            DB::commit();

            toast('Stock reject has been update successfully!', 'success');

            return redirect()->route('stock-reject.index');

        } catch (Exception $exception) {
            DB::rollback();
            toast($exception->getMessage(), 'error');
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(StockReject $stockReject)
    {

        $stock = Stock::addStock($stockReject->item_id, $stockReject->quantity);
        $stockReject->delete();

        toast('Stock reject has been deleted successfully!', 'success');

        return redirect()->route('stock-reject.index');
    }

    public function itemsByCategory($catId)
    {
        $items = Item::where('category_id', $catId)->get();

        return response()->json($items);
    }
}

resources/views/admin/stock_reject/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Admin</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Stock Reject</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">
                                    Add Stock Reject
                                    <a href="{{ route('stock-reject.index') }}" class="btn btn-primary btn-sm pull-right">
                                        <i class="la flaticon-back"></i> Back</a>
                                </div>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'stock-reject.store']) !!}

                                @include('admin.stock_reject.form')

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </div>

                                {!! Form::close() !!}

                            </div>
                        </div>
                    </div>
                </div>
            </div>

@endsection

resources/views/admin/stock_reject/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Admin</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Stock Reject</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">
                                    Edit Stock Reject
                                    <a href="{{ route('stock-reject.index') }}" class="btn btn-primary btn-sm pull-right">
                                        <i class="la flaticon-back"></i> Back </a>
                                </div>
                            </div>
                            <div class="card-body">
                                {!! Form::model($stockReject, ['route' => ['stock-reject.update', $stockReject->id]]) !!}
                                @method('put')

                                @include('admin.stock_reject.form')

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Update changes</button>
                                        </div>
                                    </div>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

@endsection

resources/views/admin/stock_reject/form.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::label('category_id', 'Category') !!} <span class="text-danger">*</span>
            {!! Form::select('category_id', $categories, null, ['id' => 'category_id', 'placeholder'=>'Select Category','class' => 'form-control']) !!}
            @error('category_id')
            <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            {!! Form::label('item_id', 'Item') !!} <span class="text-danger">*</span>
            {!! Form::select('item_id', $items, null, ['id' => 'item_id', 'placeholder'=>'Select Item','class' => 'form-control']) !!}
            @error('category_id')
            <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            {!! Form::label('quantity', 'Quantity')  !!} <span class="text-danger">*</span>
            {!! Form::text('quantity', null, ['class' => 'form-control', 'placeholder' => 'Enter Quantity', 'id' => 'quantity']) !!}

            @error('quantity')
            <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            {!! Form::label('status', 'Status') !!}
            {!! Form::select('status', ['1' => 'Active', '2' => 'Disabled'], null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::label('description', 'Description') !!}
            {!! Form::textarea('description', null, ['class' => 'form-control', 'id' => 'description']) !!}
        </div>
    </div>
</div>
@push('js')
    <script>
        $('#category_id').on('change', function (){
            var category_id = $(this).val();
            $.ajax({
                url:"{{url('admin/items-by-category')}}/"+category_id,
                type:"GET",
                dataType:'json',
                success:function(data){
                    $('#item_id').html('<option value="">Select Item</option>')
                    $.each( data, function( key, value) {
                        $('#item_id').append('<option value="'+value.id+'">'+value.item_name+'</option>')
                    });
                }
            });
         });
    </script>
@endpush

resources/views/admin/stock_reject/list.blade.php
@extends('layouts.admin')

@section('content')
    <div class="main-panel">
        <div class="content">
            <div class="page-inner">
                <div class="page-header">
                    <ul class="breadcrumbs">
                        <li class="nav-home">
                            <a href="#">
                                <i class="flaticon-home"></i>
                            </a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Admin</a>
                        </li>
                        <li class="separator">
                            <i class="flaticon-right-arrow"></i>
                        </li>
                        <li class="nav-item">
                            <a href="#">Stock Reject</a>
                        </li>
                    </ul>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-title">
                                    Stock Reject
                                    <a href="{{ route('stock-reject.create') }}" class="btn btn-primary btn-sm pull-right">
                                        <i class="fas fa-plus-circle"></i> add
                                    </a>
                                </div>
                            </div>
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Category Name</th>
                                        <th>Item Name</th>
                                        <th>Quantity</th>
                                        <th>Description</th>
                                        <th width="140">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($stockRejects as $index => $v)
                                        <tr>
                                            <th scope="row">{{ $stockRejects->firstItem() + $index }}</th>
                                            <td>{{ $v->category->category_name }}</td>
                                            <td>{{ $v->item->item_name }}</td>
                                            <td>{{ $v->quantity }}</td>
                                            <td>{{ $v->description }}</td>
                                            <td>

                                                <form action="{{ route('stock-reject.destroy', $v->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <a href="{{ route('stock-reject.edit', $v->id) }}" class="btn btn-secondary btn-xs">
                                                        <i class="fas fa-pen-square"></i> Edit
                                                    </a>
                                                    <button class="btn btn-danger btn-xs delete-button">
                                                        <i class="fas fa-trash-alt"></i> Delete
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                {!! $stockRejects->links() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('js')
    <script>
        // mortgage approval
        $(document).on('click', '.delete-button', function (e) {
            e.preventDefault();
            Swal.fire({
                title: "Are you sure to delete",
                icon: "warning",
                confirmButtonText: 'Confirm',
                showCancelButton: true,
            }).then(function (result) {
                console.log(result)
                if (result.isConfirmed) $('.delete-button').parents('form').submit();
            });
        });
    </script>
@endpush